### ISSUE TITLE
Make available on Maven Central

### ISSUE THREAD

**Issue by jessliu** [couchbase/couchbase-lite-java#34]
Similar to https://github.com/couchbase/couchbase-lite-android/issues/378

Please push officially supported builds to Maven Central for distribution. 

Requirements are as follows:
https://docs.sonatype.org/display/Repository/Central+Sync+Requirements

More information about making your project available on Central is available here: http://maven.apache.org/guides/mini/guide-central-repository-upload.html

**Comment by doruchiulan** [comment]
I have a Maven project where I will use couchbase-lite-java.

It will be used as a library on multiple systems and I am questioning myself how should I distribute it because for making it work on my system (OS X) I had to recompile the couchbase-lite-java so the native libraries were built for my system. So I wasn't able to use the dependency directly from the Maven Repository and I don't know if building jars on all platforms is the best idea to distribute my project. Just consider that some guy that will use my library wants to do a cross platform app and he uses one of my built jars, it will only work on the platform he got the jar for.

Do you think that there will be a solution for this in the future and users will be able to get the library with the right native artifacts that couchbase-lite-java use?

I am really newbie regarding this topic so I might say stupid things but maybe you can point me to some readings regarding how should I tackle this problem.

**Comment by hideki** [comment]
Building cross platform jar file that contains native library is challenging. I am considering to build native libraries separately for all major platforms. When build jar file, make jar file contains all platform dependent native libraries in one jar file. Currently our build system does not solve this problem.

**Comment by hideki** [comment]
v1.2.0 is on Maven Central.  I will close this ticket.

NOTE: Deployment on Maven Central is not automated. It is still  manual process.
